task_node:
  ros__parameters:
    max_seat_number: 0
    face_recognition:
      image_timeout_sec: 15.0
      judgment_timeout_sec: 60.0
      image_republish_interval_sec: 1.0
    navigation:
      action_name: /navigate_to_pose
      frame_id: map
      timeout_sec: 30.0
      action_server_timeout_sec: 10.0
      goal_response_timeout_sec: 10.0
      seats_json: '{"1": {"id": "1", "x": 0.5, "y": -0.12, "yaw": 0.4373379 }, "2": {"id": "2", "x": 0.51, "y": -0.55, "yaw": -0.8732543 }}'
      scan_route_json: '["1", "2"]'
      default_route_json: '[]'
      default_goal_json: '{"id": "home", "x": 0.0, "y": 0.0, "yaw": 0.0}'
